pg:
  build: .
  environment:
    - POSTGRES_PASSWORD=asf
psql:
  image: postgres
  links:
    - pg:postgres
  command: 'sh -c "exec psql -h $$POSTGRES_PORT_5432_TCP_ADDR -p $$POSTGRES_PORT_5432_TCP_PORT -U postgres"'